name = "coin-price-checker"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { ADMIN_PASSWORD = "admin123" }

[[kv_namespaces]]
binding = "PRODUCTS"
id = "86a3f08465d14695ad7fde49cf624a96"