name = "coin-price-checker"
main = "worker-v2.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { ADMIN_PASSWORD = "admin123", VERCEL_API_URL = "https://coni-price-checker.vercel.app/api/fetch-price-v2" }

[[env.production.kv_namespaces]]
binding = "PRODUCTS"
id = "86a3f08465d14695ad7fde49cf624a96"

[[env.production.d1_databases]]
binding = "DB"
database_name = "coin-price-db"
database_id = "bb8e5868-1afa-460b-91ca-6e3de07b2eea"

# [triggers]
# crons = ["*/10 * * * *"]
# 10分ごとに価格更新チェック - 現在無効化